[workspace]
members = [
  "bit_count",
  "move_squared_string",
  "buying_car",
  "your_order",
  "max_len_diff",
  "same_vectors",
  "last_dig_large_num",
  "molecule_to_atoms",
  "fibs_perimeter",
  "rain_fall",
  "granny_help",
  "weight_for_weight",
  "prime_factors",
  "phone_dir"
]
